### ISSUE TITLE
关于抓取效率的问题

### ISSUE THREAD

**Issue by Miaoz1** [gonaxx/weiboSpider#2]
首先感谢您提供的代码！然后我有一个问题：运行后抓取了五条就进入了睡眠中，并且睡眠时间是一个小时，有没有办法可以更高效的进行爬取呢？
：NoSuchElementException()
达到单时段最大次数限制。当前时间是2023-06-30 19:46:55，目前已抓取5条微博，下次抓取时间：2023-06-30 20:46:56，现在睡眠中

**Comment by gonaxx** [comment]
Sorry，我刚才试了一下，并没有复现这个问题，猜测可能是因为您的账号或者ip在单位时间内抓取的微博太多？或者关键词被屏蔽？总之，报错原因是网页上没有“下一页“这个元素，你可以在不隐藏浏览器界面的情况下查看是否果真如此。您可以等待一会儿后重新运行get_cookie，再尝试抓取。如果还存在问题，请及时告知我，谢谢！

**Comment by Miaoz1** [comment]
您好！我尝试了重新运行get_cookie,然后尝试抓取依然出现这个问题，我不太清楚如何不隐藏浏览器查看，登录后Chrome自动关闭了，运行结果如图所示，求大佬指教，谢谢！
![9b804693d1834f2086097c34166801d](https://github.com/gonaxx/weiboSpider/assets/137239242/5ca59404-b83f-4cc1-8891-4741f2a2a9f5)

**Comment by Miaoz1** [comment]
有没有可能是元素异步加载的问题呀大佬

**Comment by Miaoz1** [comment]
大佬您好，我对比了一下网页上的内容，发现是只爬取了第一页的数据然后就进入了睡眠，第二页的数据是没有爬到，是不是在跳转页面的时候遇到一些问题呀

**Comment by gonaxx** [comment]
应该是您的cookie没有成功保存，运行get_cookie以后25秒以内使用微博app扫码登录才可以。
